### PR TITLE
WIP : Transform CMakeLists.hpx to use target based directives

### PR DESCRIPTION
**Pull request by aurianer**
Use CMake target based directives to avoid global include directories and useless linkage.

### CODE REVIEW

**Comment by aurianer** [comment]
Still have some tests to perform on all the different CMake options..

**Comment by khuck** [comment]
This would break APEX builds without HPX - we might want to put the cmake modules for HPX builds into a different directory, and have another directory with the current cmake modules.  Just a thought.  Ideally, I wanted to clean up the CMake configurations for HPX and non-HPX builds, so that might not work as well...

**Comment by aurianer** [comment]
This would break APEX without HPX even if the only modified file is `CMakeLists.hpx` ? And that this file is called only when `HPX_WITH_APEX=ON` ? ^^

**Comment by khuck** [comment]
Ah, I see - you created new files.  I thought you were modifying existing cmake modules.  I didn't understand what github was showing me.

I'll try a build with your changes... is the goal of this PR to build all the dependencies?

**Comment by khuck** [comment]
On second thought... there are already CMake modules to build the dependencies (see FindBFD.cmake for example).  How is this different?

**Comment by khuck** [comment]
Ah, never mind - I see that you just modularized things.  The build succeeded, so I'll merge it

**Pull request merged**
