### PR TITLE
Fix a gcc-8 warning about strncpy

### PR DESCRIPTION
**Pull request by biddisco**

### CODE REVIEW

**Comment by biddisco** [comment]
NB. didn't actually test that this is correct.

**Comment by khuck** [comment]
GCC 8 considers strncpy a bad thing now?  Looks fine to me, thanks.  I'll merge it in, and if the buildbot fails, I'll fix it.

**Comment by khuck** [comment]
The macro above needs the same fix

**Comment by khuck** [comment]
which it now has

**Pull request merged**
